class Recipe {
  final String name;
  final String asset;
  final String ingredientsQuantity;
  final List<Ingredient> ingredients;
  final List<Instr> instructions;
  const Recipe({this.name, this.asset, this.ingredients = const [], this.ingredientsQuantity, this.instructions = const []});
}

class Ingredient {
  final String label;
  final String quantity;
  const Ingredient(this.label, this.quantity);
}

class Instr {
  final String content;
  const Instr(this.content);
}

const data = [
  // Sucré
  [
    Recipe(
      name: "Carrot cake",
      asset: "carrot_cake.jpg",
      ingredientsQuantity: "pour 8 personnes",
      ingredients: [
        Ingredient("farine", "250g"),
        Ingredient("levure", "1 sachet"),
        Ingredient("bicarbonate", "1 cuillère à café"),
        Ingredient("canelle", "1 cuillère à café 1/2"),
        Ingredient("noix de muscade", "1/4 cuillère à café"),
        Ingredient("sel", "1/2 cuillère à café"),
        Ingredient("noix de pécan", "(pour le décor)"),
        Ingredient("huile", "180mL"),
        Ingredient("oeufs", "4 gros"),
        Ingredient("sucre brun", "300g"),
        Ingredient("sucre blanc", "100g"),
        Ingredient("compote de pomme", "125g"),
        Ingredient("vanille", "1 cuillère à café"),
        Ingredient("carottes", "300g"),
        Ingredient("philadelphia", "226g"),
        Ingredient("beurre doux", "115g"),
        Ingredient("sucre glace", "240g"),
        Ingredient("extrait de vanille", "1 cuillère à café"),
      ],
      instructions: [
        Instr("Dans un premier bol mélanger la farine, la levure, le bicarbonate, la canelle, le sel et la noix de muscade."),
        Instr("Dans un second bol mélanger l'huile, les oeufs, les sucres brun & blanc, la compote, la vanille, puis les carottes."),
        Instr("Verser le contenu du bol 2 dans le bol 1 et mélanger jusqu'à obtention d'une pâte homogène."),
        Instr("Puis cuire à 180°C pendant 35 minutes."),
        Instr("Pour le glaçage, dans un saladier lisser au mixer plongeant le philadephia, y ajouter le beurre et mixer 30 secondes."),
        Instr("Ajouter le sucre, l'extrait de vanille si désiré et mixer pour avoir une crème bien lisse. "),
        Instr("Couper le gâteau en 2 dans l'épaisseur et monter le gâteau."),
        Instr("On mettra une moitié de gateau, du glaçage, l'autre moitié de gâteau et on recouvre de glaçage l'ensemble du gâteau ainsi monté."),
        Instr("On décorera de noix de pécan."),
        Instr("Laisser plusieurs heures au réfrigérateur avant dégustation."),
      ],
    ),
    Recipe(
      name: "Pancake",
      asset: "pancake.jpg",
      ingredientsQuantity: "pour 2 personnes",
      ingredients: [
        Ingredient("farine", "125g"),
        Ingredient("sachet de levure", "1/2"),
        Ingredient("oeuf", "1"),
        Ingredient("sucre roux", "15g"),
        Ingredient("beurre salé", "35g"),
        Ingredient("lait", "10cL"),
        Ingredient("rhum", "5cL"),
      ],
      instructions: [
        Instr("Faire fondre le beurre."),
        Instr("Dans un saladier mettre la farine, la levure et le sucre, mélanger puis faire un puit."),
        Instr("Ajouter ensuite l'oeuf et fouetter doucement pour éviter les grumeaux."),
        Instr("Incorporer le beurre fondu en continuant à fouetter pour faciliter le mélange, " +
            "puis délayer progressivement avec le lait et le rhum en continuant à fouetter jusqu'à obtention d'une pâte bien lisse.\n" +
            "Attention la pâte est bien plus épaisse qu'une pâte à crêpe mais plus fluide qu'une pâte à gâteau."),
        Instr("La pâte peut être utilisée dès maintenant mais supporte très bien le passage au réfrigérateur."),
        Instr("Faire cuire à la poêle à feux moyen en mettant une petite dose de pâte sans ajout de matière grasse nécessaire."),
        Instr("Retourner le pancake quand des bulles se forment à la surface. "),
        Instr(
            "À déguster chaud avec du sirop d'érable, ou du sucre glace, ou de la pâte à tartiner. La garniture n'a de limite que votre imagination et votre goût !"),
      ],
    ),
    Recipe(
      name: "Galette à la frangipane",
      ingredientsQuantity: "pour 6 personnes",
      asset: "galette_cuite.jpg",
      ingredients: [
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
      ],
      instructions: [
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
      ],
    ),
    Recipe(
      name: "Muesli",
      asset: "muesli.jpg",
      ingredientsQuantity: "pour ~700g",
      ingredients: [
        Ingredient("flocons d'avoine", "300g"),
        Ingredient("pépites de chocolat", "100g"),
        Ingredient("graines de tournesol", "30g"),
        Ingredient("eau chaude", "150mL"),
        Ingredient("miel", "80g"),
        Ingredient("fleur de sel", "3 pincées"),
        Ingredient("noix de coco râpée", "50g"),
      ],
      instructions: [
        Instr("BOL 1 : Mélanger les flocons d'avoine, les graines de tournesol, la fleur de sel et la noix de coco râpée."),
        Instr("BOL 2 : Mélanger l'eau et le miel"),
        Instr("Verser le bol 2 dans le 1 et bien mélanger pour que tout soit bien humide et collant. "),
        Instr("Répartir le mélange ainsi obtenu sur une plaque de cuisson préalablement recouverte de papier cuisson."),
        Instr("Cuire 40 minutes à 150°C en remuant régulièrement pour que ça ne roussisse pas !"),
        Instr("Si besoin rajouter du miel pendant cuisson et mélanger pour coller d'avantage les céréales entre elles. "),
        Instr("Laisser refroidir puis ajouter les pépites de chocolat. "),
        Instr("Conserver dans une boîte en métal pour préserver le croquant."),
      ],
    ),
  ],
  // Salé
  [
    Recipe(
      name: "Flammekueche",
      asset: "flammekueche.jpg",
      ingredientsQuantity: "pour 4 à 6 personnes",
      ingredients: [
        Ingredient("pâte feuilletée ou pâte à pizza", "1"),
        Ingredient("alumettes fumées", "150g"),
        Ingredient("oignon déshydraté", "1"),
        Ingredient("gruyère râpé", "quantité suffisante"),
        Ingredient("crème fraiche liquide", "20cL"),
      ],
      instructions: [
        Instr("Recouvrir la pâte de crème fraiche, puis d'allumettes fumées, d'oignons déshydratés et de gruyère râpé."),
        Instr("Cuire au four à 180°C pendant ~25min"),
      ],
    ),
    Recipe(
      name: "Courge butternut gratinée",
      asset: "courge_butternut.jpg",
      ingredients: [
        Ingredient("courge butternut", "1"),
        Ingredient("petit chèvre", "1"),
        Ingredient("pincée de sel", "1"),
        Ingredient("pincée de poivre", "1"),
        Ingredient("pincée d'herbes de provence", "1"),
        Ingredient("crème fraiche liquide", "20cL"),
      ],
      instructions: [
        Instr("Dans un bol mélanger le chèvre coupé en petits dés avec la crème, assaisonner."),
        Instr("Couper la courge butternut en deux puis retirer les graines en faisant un creux suffisant pour pouvoir y verser la préparation crème-chèvre."),
        Instr("Cuire au four à 180°C pendant 1h à chaleur tournante"),
      ],
    ),
    Recipe(
      name: "Pâte à pizza aux herbes de provence",
      asset: "pate_pizza_herbes_provence.jpg",
      ingredientsQuantity: "pour 4 à 6 personnes",
      ingredients: [
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
      ],
      instructions: [
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
      ],
    ),
    Recipe(
      name: "Pizza chèvre miel",
      asset: "pizza_chevre_miel.jpg",
      ingredientsQuantity: "pour 4 à 6 personnes",
      ingredients: [
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
      ],
      instructions: [
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
      ],
    ),
    Recipe(
      name: "Chirashi",
      asset: "chirashi1.jpg",
      ingredientsQuantity: "pour 2 personnes",
      ingredients: [
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
      ],
      instructions: [
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
      ],
    ),
    Recipe(
      name: "Gnocchis courgettes et crevettes",
      asset: "gnocchis_courgettes_crevettes.jpg",
      ingredientsQuantity: "pour 2 personnes",
      ingredients: [
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
      ],
      instructions: [
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
      ],
    ),
    Recipe(
      name: "Pâtes aux épinards et roquefort",
      asset: "pates_epinards_roquefort.jpg",
      ingredientsQuantity: "pour 2 personnes",
      ingredients: [
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
      ],
      instructions: [
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
      ],
    ),
    Recipe(
      name: "Pissaladière",
      asset: "pissaladiere.jpg",
      ingredientsQuantity: "pour 6 personnes",
      ingredients: [
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
      ],
      instructions: [
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
      ],
    ),
    Recipe(
      name: "Quiche aux poireaux",
      asset: "quiche_poireaux.jpg",
      ingredientsQuantity: "pour 6 personnes",
      ingredients: [
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
      ],
      instructions: [
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
      ],
    ),
    Recipe(
      name: "Burger",
      asset: "burger.jpg",
      ingredientsQuantity: "pour 2 personnes",
      ingredients: [
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
      ],
      instructions: [
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
      ],
    ),
    Recipe(
      name: "Bagnat",
      asset: "bagnat.jpg",
      ingredientsQuantity: "pour 2 personnes",
      ingredients: [
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
      ],
      instructions: [
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
      ],
    ),
    Recipe(
      name: "Risotto",
      asset: "risotto.jpg",
      ingredientsQuantity: "pour 2 personnes",
      ingredients: [
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
        Ingredient("", ""),
      ],
      instructions: [
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
        Instr(""),
      ],
    ),
  ],
  // Boissons
  [
    Recipe(
      name: "Sangriananas",
      asset: "sangriananas.jpg",
      ingredientsQuantity: "pour 2 bouteilles",
      ingredients: [
        Ingredient("conserve d'ananas sans sucre ajouté", "560g"),
        Ingredient("cidre doux", "75cL"),
        Ingredient("Bourgogne Aligoté", "60cL"),
        Ingredient("vanille en poudre", "1/2 cuillère à café"),
        Ingredient("sirop de sucre de Canne ou cassonade", "8 cuillères à café"),
      ],
      instructions: [
        Instr("Couper l'ananas en petits cubes qui puissent passer le goulot de votre bouteille."),
        Instr("Mélanger tous les ingrédients ensemble dans un grand saladier."),
        Instr("Prendre soin de bien mélanger la vanille pour éviter les \"grumeaux\"."),
        Instr("Transvaser l'ensemble dans deux bouteilles y compris les morceaux d'ananas."),
        Instr("Laisser macérer ainsi au réfrigérateur pendant deux à trois jours avant de déguster bien frais."),
        Instr("À consommer dans la semaine après la fabrication."),
      ],
    ),
  ]
];
